---

- name:restart server
  command:/usr/sbin/shutdown -r +1
  async:1
  poll: 0
  ignore_errors: true
  
- name: wait for server to restart
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    state: started
    delay: 90
    timeout: 300
  become: false
  delegate_to: localhost

...